version: '3'
services:
  cms-etutor:
    image: tungduy/cms-etutor
    environment:
      NODE_ENV: production
      REACT_APP_PHP_SERVER: ${PHP_SERVER}
      REACT_APP_NODE_SERVER: ${NODE_SERVER}
      REACT_APP_AWS_S3: ${AWS_S3}