version: '3'
services:
  cms-etutor:
    container_name: cms-etutor
    ports: 
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    networks:
      - fbeta-networks
networks: 
  fbeta-networks:
    external: true
