
version: '3'
services:
  cms-etutor:
    build:
      context: .
    image: tungduy/cms-etutor
    volumes: 
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development