version: '3'
services:
  react-app:
    build:
      context: .
    container_name: react-app
    ports: 
      - 3030:3030
    volumes: 
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    environment:
      PORT: 3030
    networks:
      - cms-www-net
networks: 
  cms-www-net:
    external: true
# docker network create cms-www-net
# docker network create fbeta-networks